### ISSUE TITLE
Bad auto-focus

### ISSUE THREAD

**Issue by dimitrovskif** [dlazaro66/QRCodeReaderView#15]
I think this project doesn't use the parts of ZXing that do the autofocusing.

 It seems to only do it at big intervals, the image is really blurry which means I have to wait 10-15 seconds in order to scan a QR code.

I'm running latest version on Galaxy S3 (Android 4.4) with zxing-core:3.2

**Comment by dlazaro66** [comment]
Hi!
> I think this project doesn't use the parts of ZXing that do the autofocusing.

As you can see here, I'm using exactly the same AutoFocusManager Class from Zxing project:
https://github.com/dlazaro66/QRCodeReaderView/blob/master/QRCodeReaderView-lib/qrcodereaderview/src/main/java/com/google/zxing/client/android/camera/open/AutoFocusManager.java
But instead of original 2sec to focus, I changed it for 5 sec. It worked better for me when using this project for augmented reality purposes. You can clone this repo and set this value as you need if that doesn't fits to you.

**Comment by dimitrovskif** [comment]
I forgot to post, half an hour after posting this issue I found out the reason is the `AUTO_FOCUS_INTERVAL_MS` - ZXing feels better because it does it 2.5x more than QRCodeReaderView :)

Thank you for responding anyway.

**Comment by eGorets** [comment]
```
public class ReflectionUtils {

    public static void performInjection() {
        injectClassField(AutoFocusManager.class, "AUTO_FOCUS_INTERVAL_MS", 2000L);
    }

    private static void injectClassField(Class clazz, String fieldStr, long newValue) {
        try {
            final Field field = clazz.getDeclaredField(fieldStr);
            if (field != null) {
                field.setAccessible(true);
                Object obj = null;
                field.set(obj, newValue);
            }
        } catch (Exception e) {
            Ln.e(e, "%s injection failed for field:%s", clazz.getSimpleName(), fieldStr);
        }
    }
}

```
