### ISSUE TITLE
Scanner View Is upside down

### ISSUE THREAD

**Issue by adityagohad** [dlazaro66/QRCodeReaderView#37]
When I put QRCodeReaderView into the layout camera input is all upside down

**Comment by agaurav77** [comment]
I can confirm this for Nexus 5x, so I think the setCameraDisplayOrientatio(...) function isn't working well.

**Comment by spong** [comment]
This was fixed and merged into master as part of PR #35 

That said, the version distributed via [jcenter](https://bintray.com/dlazaro66/maven/QRCodeReaderView/view#release) is from March 2015, so a little out of date. I tried grabbing it via [jitpack](https://jitpack.io/#dlazaro66/QRCodeReaderView), but because of the project structure you'll get a ['project app resolves to an APK' build error](https://github.com/jitpack/jitpack.io/issues/69).

So for the time being, just download the sources (QRCodeReaderView-lib) and include it in your project ala http://stackoverflow.com/a/29791978 (ignoring git submodule piece if you'd like).

**Comment by agaurav77** [comment]
Yeah, did that, worked :) I had to change the lines specifying the maven plugin version from 1.2 to 1.3 for this to work however (did a PR for that as well, still to be discussed).

**Comment by cnevinc** [comment]
awesome!
