### ISSUE TITLE
Import Project

### ISSUE THREAD

**Issue by rohitshampur** [dlazaro66/QRCodeReaderView#42]
Please remove *.iml and *.idea from .gitignore and rebuild the project and push  so we can import it into android studio directly from git

**Comment by saguinav** [comment]
*.iml and *.idea files are created by the IDE when the project is imported and they should not be commited into the repo. In order to import this project into Android Studio you should:
1. Checkout the repo.
2. Open Android Studio.
3. Go to File > Open...
4. Look for the directory where you did checkout the project and select the root **build.gradle** file.

I hope it works for you. Otherwise let me know and I will be happy to help.
